<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.8" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.8" />

	
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

	
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />

	
		<PackageReference Include="NUnitTestAdapter.WithFramework" Version="2.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Demo_Product.BusinessLayer\Demo_Product.BusinessLayer.csproj" />
		<ProjectReference Include="..\Demo_Product.DataAccessLayer\Demo_Product.DataAccessLayer.csproj" />
		<ProjectReference Include="..\Demo_Product.EntityLayer\Demo_Product.EntityLayer.csproj" />
	</ItemGroup>
</Project>
